name: collect_papers

on: 
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # 您可以指定所需的Python版本
  
      - name: Install dependencies
        run: pip install requests  # 安装requests库用于API调用
  
      - name: Create papers directory
        run: mkdir -p papers  # 创建一个名为papers的文件夹，如果它不存在的话
  
      - name: Download daily papers
        run: |
          import datetime
          import requests
          from dateutil.relativedelta import relativedelta

          # 获取当前日期
          cur_date = datetime.datetime.now().date() - datetime.timedelta(days=1)
          end_date = cur_date - relativedelta(days=30)

          while cur_date >= end_date:
              # 构建包含日期和文件夹的文件名
              file_name = f"papers/daily_papers_{cur_date}.json"
              # 发送GET请求获取论文
              response = requests.get(f"https://huggingface.co/api/daily_papers?date={cur_date.strftime('%Y-%m-%d')}")
              if response.status_code == 200:
                  # 将响应内容写入新文件
                  with open(file_name, "w") as file:
                      file.write(response.text)
                  break  # 成功获取数据后退出循环
              cur_date -= datetime.timedelta(days=1)  # 移至下一天

      - name: Commit Changes
        run: |  
          git config --global user.name 'King guys'
          git config --global user.email 'qgesx2003123@163.com'
          git pull
          git add .
          git commit -m "Automated report"
          git push
