name: Generate Historical Reports

on:
  workflow_dispatch:

jobs:
  generate_reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-zenhei fonts-noto-cjk
          
      - name: List existing data files
        run: |
          echo "Existing data files in Paper_metadata_download:"
          ls -l Paper_metadata_download/*.json || true
          
      - name: Generate Historical Reports
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          # 确保目录存在
          mkdir -p Paper_metadata_download
          mkdir -p newsletters
          mkdir -p audio
          mkdir -p images
          mkdir -p logs
          mkdir -p stats
          
          # 运行处理脚本
          python process_historical_data.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Generate historical reports for all existing data" || echo "No changes to commit"
          git push 