name: Generate Historical Reports

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: '开始日期 (YYYY-MM-DD)'
        required: true
        type: string
      end_date:
        description: '结束日期 (YYYY-MM-DD)'
        required: true
        type: string

jobs:
  generate_reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-zenhei fonts-noto-cjk
          
      - name: List existing data files
        run: |
          echo "Existing data files in Paper_metadata_download:"
          ls -l Paper_metadata_download/*.json || true
          
      - name: Generate Historical Reports
        run: |
          # 确保目录存在
          mkdir -p Paper_metadata_download
          mkdir -p daily_paper_output
          mkdir -p daily_paper_output/audio
          mkdir -p daily_paper_output/images
          mkdir -p daily_paper_output/newsletter
          
          # 运行处理脚本
          python process_historical_data.py "${{ github.event.inputs.start_date }}" "${{ github.event.inputs.end_date }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Generate historical reports from ${{ github.event.inputs.start_date }} to ${{ github.event.inputs.end_date }}" || echo "No changes to commit"
          git push 