name: HF-day-paper+GLMs-api-clean

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  structure-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai tqdm
        
    - name: Structure daily paper data
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python HF-day-paper+GLMs-api-clean.py
        
    - name: Commit changes
      run: |
        git config --global user.name 'King guys'
        git config --global user.email '68528929+2404589803@users.noreply.github.com'
        git add .
        git commit -m "每日论文结构化文件推送" || echo "No changes to commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
