name: HF-day-paper+GLMs-api-cow

on:
  schedule:
    # Runs at 23:00 UTC every day (which is 7:00 AM Beijing Time)
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tqdm

    - name: Run the script
      run: |
        python HF-day-paper+GLMs-api-cow.py
