name: Download Paper Metadata

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.download.outputs.status }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
    
    - name: Download paper metadata
      id: download
      run: |
        python Paper_metadata_download.py
      continue-on-error: true
    
    - name: Check download status
      id: check
      run: |
        if [ $? -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=no_data" >> $GITHUB_OUTPUT
          echo "No papers available today, workflow will end here."
          exit 0
        fi
    
    - name: Commit and push if there are changes
      if: steps.check.outputs.status == 'success'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Paper_metadata_download/
        git commit -m "Update paper metadata" || exit 0
        git push



