name: Paper_metadata_download

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 2:00 (北京时间 10:00) 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest
    outputs:
      download_status: ${{ steps.download.outputs.status }}
      date: ${{ steps.set-date.outputs.date }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set date
      id: set-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Download paper metadata
      id: download
      run: |
        python Paper_metadata_download.py
        if [ $? -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
        fi
    
    - name: Check download result
      id: check
      run: |
        DATE=$(date +'%Y-%m-%d')
        FILE="Paper_metadata_download/${DATE}.json"
        if [ -f "$FILE" ] && [ -s "$FILE" ]; then
          echo "Papers downloaded successfully"
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "No papers available or download failed"
          echo "status=no_data" >> $GITHUB_OUTPUT
          exit 0
        fi
    
    - name: Commit and push if there are changes
      if: steps.check.outputs.status == 'success'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # 拉取最新的更改
        git pull origin main --rebase
        
        # 添加和提交更改
        git add Paper_metadata_download/
        git commit -m "Update paper metadata for ${{ steps.set-date.outputs.date }}" || exit 0
        
        # 推送更改（如果失败则重试）
        n=0
        until [ $n -ge 3 ]
        do
          git push && break
          n=$[$n+1]
          git pull origin main --rebase
        done



