name: Paper Metadata Download

on:
  schedule:
    - cron: '0 17 * * 2-6'

jobs:
  paper_metadata_download:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Download paper metadata
      env:
        SAVE_FOLDER: ${{ github.workspace }}/daily_papers
      run: python paper_metadata_download.py
    - name: Check and commit changes
      run: |
        # Add a simple script to check for changes before committing
        if [ -s "$SAVE_FOLDER" ]; then
          echo "Changes found in $SAVE_FOLDER"
          git config user.name 'King guys'
          git config user.email '68528929+2404589803@users.noreply.github.com'
          git add daily_papers
          git commit -m "每日论文"
          git push
        else
          echo "No changes found. Not committing."
        fi